name: Deploy to AWS
on:
   workflow_dispatch:
   push:
    branches:
      - main

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  terraform-plan:
      name: "Terraform Plan"
      runs-on: ubuntu-latest
      outputs:
        tf_workspace: ${{ steps.env-vars.outputs.tf_workspace }}
      defaults:
        run:
          shell: bash

      steps:
        # 1. Check out the repository code
        - name: Checkout Code
          uses: actions/checkout@v4

        # 2. Add terraform in the flow 
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
          terraform_version: 1.13.3
        - name: Setup TFLint
          uses: terraform-linters/setup-tflint@v3
          with:
            tflint_version: v0.52.0

         # 3. initialising TFlint in the repo    
        - name: Init TFLint
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: tflint --init


